#!/usr/bin/env python3
"""
Generated by Claude Code Pattern Analyzer
Pattern: chord_cut (bilateral cuts on cylindrical part)
Confidence: 0.91 (weighted average from 5 agents)

Analysis Summary:
================
Agent Consensus:
- All 5 agents detected Circle geometry with diameter=90mm
- All agents detected bilateral chord cuts (left_side + right_side)
- 4/5 agents report height=27mm, 1/5 reports 5mm → Using majority: 27mm
- All agents mention 78mm flat-to-flat distance

Audio Transcription:
- "Chapa de diâmetro 90mm Raio de 45mm e 2 linhas a distância de 78mm"
- Confirms: diameter 90mm, radius 45mm, 2 parallel lines at 78mm distance

Pattern Detection:
- Type: chord_cut (bilateral cuts on circle)
- Rationale: Agents detected symmetric cuts on "left_side" and "right_side"
- Visual evidence: Flat parallel sides visible in top views
- Mathematical validation: Cut depth = (90-78)/2 = 6mm per side

Extracted Parameters:
- diameter = 90.0mm (from all agents)
- radius = 45.0mm (from audio + agents)
- flat_to_flat = 78.0mm (from audio "distância de 78mm")
- height = 27.0mm (majority vote from agents 0,2,3,4)
"""

import sys
import json
from pathlib import Path

# Add visioncad src directory to path for imports
# Path structure: .../visioncad/src/docs/outputs/visioncad/SESSION_ID/claude_analysis.py
# We need: .../visioncad/src/ (5 parents up)
visioncad_src = Path(__file__).parent.parent.parent.parent.parent
sys.path.insert(0, str(visioncad_src))

# Import from semantic_builder (CRITICAL: in visioncad/src/, NOT semantic_geometry!)
from semantic_builder import PartBuilder

# ===== Parameter Extraction =====

# From agent consensus (all 5 agents agree)
diameter = 90.0  # mm
radius = diameter / 2  # 45.0 mm

# From audio transcription: "2 linhas a distância de 78mm"
flat_to_flat = 78.0  # mm

# From agent majority (4/5 agents report 27mm)
height = 27.0  # mm

# ===== Part Construction =====

# Create PartBuilder instance
builder = PartBuilder(name="chapa_circle_90mm")

# Add chord cut extrude (handles Arc + Line geometry automatically!)
builder.add_chord_cut_extrude(
    radius=radius,
    flat_to_flat=flat_to_flat,
    height=height
)

# ===== Generate Semantic JSON =====

semantic = builder.to_dict()

# Write to session directory
output_file = Path(__file__).parent / "semantic.json"
with open(output_file, 'w', encoding='utf-8') as f:
    json.dump(semantic, f, indent=2, ensure_ascii=False)

# ===== Success Report =====

print(f"[OK] Semantic JSON generated: {output_file.name}")
print(f"")
print(f"Pattern: chord_cut")
print(f"Parameters:")
print(f"  - radius: {radius} mm")
print(f"  - flat_to_flat: {flat_to_flat} mm")
print(f"  - height: {height} mm")
print(f"  - cut_depth_per_side: {(diameter - flat_to_flat) / 2} mm")
print(f"")
print(f"Confidence: 0.91")
print(f"Agent consensus: 5/5 agents detected bilateral chord cuts")
