{
  "part": {
    "name": "cylinder_90x6_with_2cuts",
    "units": "mm",
    "metadata": {
      "created_by": "semantic-geometry-builder",
      "timestamp": "2025-11-06T20:54:49.678931Z",
      "video_file": "C:\\Users\\conta\\Downloads\\WhatsApp Video 2025-11-06 at 16.36.07.mp4",
      "frames_analyzed": 89,
      "visual_confidence": 0.8939999999999999,
      "audio_transcription": "Chapa de diâmetro 90mm Raio de 45mm e 2 linhas a distância de 78mm",
      "created_with": "visioncad_runner.py"
    },
    "work_plane": {
      "type": "primitive",
      "face": "frontal"
    },
    "features": [
      {
        "id": "extrude_0",
        "type": "Extrude",
        "sketch": {
          "plane": {
            "type": "work_plane"
          },
          "geometry": [
            {
              "type": "Circle",
              "center": {
                "x": 0,
                "y": 0
              },
              "diameter": {
                "value": 90.0,
                "unit": "mm"
              }
            }
          ]
        },
        "parameters": {
          "distance": {
            "value": 6.9,
            "unit": "mm"
          },
          "direction": "normal",
          "operation": "new_body"
        }
      },
      {
        "id": "cut_1",
        "type": "Cut",
        "sketch": {
          "plane": {
            "type": "work_plane"
          },
          "geometry": [
            {
              "type": "Rectangle",
              "center": {
                "x": 0,
                "y": 0
              },
              "width": {
                "value": 90.0,
                "unit": "mm"
              },
              "height": {
                "value": 6.0,
                "unit": "mm"
              }
            }
          ]
        },
        "parameters": {
          "distance": {
            "value": 11.3,
            "unit": "mm"
          },
          "direction": "normal",
          "cut_type": "distance"
        }
      },
      {
        "id": "cut_2",
        "type": "Cut",
        "sketch": {
          "plane": {
            "type": "work_plane"
          },
          "geometry": [
            {
              "type": "Rectangle",
              "center": {
                "x": 0,
                "y": 0
              },
              "width": {
                "value": 90.0,
                "unit": "mm"
              },
              "height": {
                "value": 6.0,
                "unit": "mm"
              }
            }
          ]
        },
        "parameters": {
          "distance": {
            "value": 4.7,
            "unit": "mm"
          },
          "direction": "normal",
          "cut_type": "distance"
        }
      }
    ]
  }
}