#!/usr/bin/env python3
"""
Generated by Claude Code Pattern Analyzer
Pattern: hollow_cylinder
Confidence: 0.95

Analysis:
- All 5 agents report Circle (OD=50mm, ID=40mm) with height=16mm
- All 5 agents report 4 radial slots with length=20mm, depth=7mm
- Audio: "Diâmetro externo 50 mm Diâmetro interno 40 mm Comprimento total 16 mm
         Rasgo 20 mm Profundidade do rasgo 7 mm 4 rasgos por iguais"
- Pattern: Hollow cylinder (bushing/sleeve)
- Note: Radial slots are complex features that will be approximated or omitted for initial CAD export
"""

import sys
import json
from pathlib import Path

# Add visioncad/src to path for semantic_builder
visioncad_src = Path(__file__).parent.parent.parent.parent.parent
sys.path.insert(0, str(visioncad_src))

from semantic_builder import PartBuilder

# Extracted parameters from agent results
# All 5 agents report identical dimensions (high confidence)
outer_diameter = 50.0  # From agent_results[*].base_geometry.dimensions.outer_diameter
inner_diameter = 40.0  # From agent_results[*].base_geometry.dimensions.inner_diameter
height = 16.0          # From agent_results[*].base_geometry.dimensions.height

# Create part using PartBuilder
builder = PartBuilder("cilindro_tubular_50x40x16")

# Step 1: Create outer cylinder (OD=50mm, height=16mm)
builder.add_circle_extrusion(
    diameter=outer_diameter,
    extrude_distance=height,
    center=(0, 0)
)

# Step 2: Remove inner cylinder to create hollow tube (ID=40mm)
# Access the underlying SemanticGeometryBuilder to add the cut
builder.builder.add_circle_cut(
    center=(0, 0),
    diameter=inner_diameter,
    cut_distance=height,
    cut_type="through_all",
    reference_feature_id="feature_1"  # Reference the outer cylinder
)

# Note: The 4 radial slots are complex features that require:
# - Rectangular sketches positioned radially
# - Cuts oriented perpendicular to the circular surface
# - Polar pattern transformation
#
# For initial CAD export, we're creating the base hollow cylinder.
# Radial slots can be added manually in FreeCAD or implemented in a future iteration
# with more sophisticated sketch positioning support.

# Generate semantic JSON
part_dict = builder.to_dict()

# Write to file
output_file = Path(__file__).parent / "semantic.json"
with open(output_file, 'w', encoding='utf-8') as f:
    json.dump(part_dict, f, indent=2, ensure_ascii=False)

print(f"[OK] Semantic JSON generated: {output_file}")
print(f"   Pattern: hollow_cylinder")
print(f"   Base: OD={outer_diameter}mm, ID={inner_diameter}mm, H={height}mm")
print(f"   Note: 4 radial slots (L=20mm, D=7mm) detected but not exported yet")
print(f"   Recommendation: Add slots manually in FreeCAD or implement advanced sketch positioning")
