"""
Claude Code Analysis for VisionCAD Pattern Recognition
Generated by: Claude Code (Sonnet 4.5)
Session: 2025-11-10_160705

PART ANALYSIS:
==============
Based on 5 agent consensus analysis of 119 frames + audio transcription.

DETECTED FEATURES:
1. Base Cylinder: 75mm diameter x 11mm height
2. Central Hole: 30mm diameter, through-all
3. Polar Hole Pattern: 3x 9mm holes on 50mm BCD, 120° spacing, through-all
4. Counterbore Pattern: 3x 15mm diameter x 9mm depth, aligned with polar holes

TRANSCRIPTION:
"Diâmetro externo, 75 milímetros, diâmetro interno, 30 milímetros.
Furo rebaixo, 15 milímetros, centro de furação, 50 milímetros,
tamanho do furo, 9 milímetros, 3 furos.
Rebaixo de profundidade de 9 milímetros e diâmetro do rebaixo de 15 milímetros."
"""

import sys
import math
import json
from pathlib import Path

# Add VisionCAD src to path (5 parents up from claude_analysis.py)
sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent.parent))

# CRITICAL: Import from semantic_builder (local), NOT semantic_geometry (external)
from semantic_builder import SemanticGeometryBuilder

# =============================================================================
# EXTRACTED PARAMETERS FROM AGENT CONSENSUS
# =============================================================================

# Base cylinder (unanimous across all agents)
base_diameter = 75.0  # mm
base_height = 11.0    # mm (estimated from side views by agent 0)

# Central through-hole (unanimous)
central_hole_diameter = 30.0  # mm

# Polar hole pattern (3 holes, unanimous)
polar_hole_diameter = 9.0       # mm
polar_hole_count = 3            # holes
polar_bolt_circle_dia = 50.0    # mm (BCD)
polar_angle_spacing = 120.0     # degrees

# Counterbore pattern (aligned with polar holes)
counterbore_diameter = 15.0   # mm
counterbore_depth = 9.0       # mm

# =============================================================================
# BUILD SEMANTIC GEOMETRY
# =============================================================================

builder = SemanticGeometryBuilder("flange_75mm_3hole_counterbore")

# FEATURE 1: Base cylinder (75mm x 11mm)
builder.add_circle_extrusion(
    center=(0, 0),
    diameter=base_diameter,
    extrude_distance=base_height
)

# FEATURE 2: Central through-hole (30mm)
builder.add_circle_cut(
    center=(0, 0),
    diameter=central_hole_diameter,
    cut_type="through_all"
)

# FEATURE 3-5: Polar hole pattern (3x 9mm holes on 50mm BCD)
# Calculate positions on bolt circle
pattern_radius = polar_bolt_circle_dia / 2.0  # 25mm

for i in range(polar_hole_count):
    # Calculate angle (0°, 120°, 240°)
    angle_deg = i * polar_angle_spacing
    angle_rad = math.radians(angle_deg)

    # Calculate (x, y) position
    x = pattern_radius * math.cos(angle_rad)
    y = pattern_radius * math.sin(angle_rad)

    # Add through-hole
    builder.add_circle_cut(
        center=(round(x, 2), round(y, 2)),
        diameter=polar_hole_diameter,
        cut_type="through_all"
    )

# FEATURE 6-8: Counterbore pattern (3x 15mm x 9mm, aligned with polar holes)
for i in range(polar_hole_count):
    # Same positions as polar holes
    angle_deg = i * polar_angle_spacing
    angle_rad = math.radians(angle_deg)

    x = pattern_radius * math.cos(angle_rad)
    y = pattern_radius * math.sin(angle_rad)

    # Add counterbore (partial depth cut)
    builder.add_circle_cut(
        center=(round(x, 2), round(y, 2)),
        diameter=counterbore_diameter,
        cut_type="distance",
        cut_distance=counterbore_depth
    )

# =============================================================================
# GENERATE SEMANTIC JSON
# =============================================================================

semantic = builder.build()

# Save to session directory
output_path = Path(__file__).parent / "semantic.json"
with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(semantic, f, indent=2, ensure_ascii=False)

print(f"[OK] Semantic JSON generated: {output_path.name}")
print(f"[OK] Features: {len(semantic['part']['features'])}")
print(f"[OK] Part name: {semantic['part']['name']}")

# =============================================================================
# SUMMARY
# =============================================================================
print("\n" + "="*70)
print("CLAUDE CODE ANALYSIS SUMMARY")
print("="*70)
print(f"Base Cylinder:      {base_diameter}mm diameter x {base_height}mm height")
print(f"Central Hole:       {central_hole_diameter}mm diameter (through)")
print(f"Polar Holes:        {polar_hole_count}x {polar_hole_diameter}mm on {polar_bolt_circle_dia}mm BCD")
print(f"Counterbores:       {polar_hole_count}x {counterbore_diameter}mm diameter x {counterbore_depth}mm depth")
print(f"Total Features:     {len(semantic['part']['features'])}")
print(f"Confidence:         High (unanimous agent consensus)")
print("="*70)
