{
  "part": {
    "name": "cylinder_90x6",
    "units": "mm",
    "metadata": {
      "created_by": "semantic-geometry-builder",
      "timestamp": "2025-11-06T21:42:55.085980Z",
      "video_file": "C:\\Users\\conta\\.claude\\skills\\recad\\src\\tests\\temp\\test_video.mp4",
      "frames_analyzed": 0,
      "visual_confidence": 0.95,
      "audio_transcription": "",
      "created_with": "recad_runner.py"
    },
    "work_plane": {
      "type": "primitive",
      "face": "frontal"
    },
    "features": [
      {
        "id": "extrude_0",
        "type": "Extrude",
        "sketch": {
          "plane": {
            "type": "work_plane"
          },
          "geometry": [
            {
              "type": "Circle",
              "center": {
                "x": 0,
                "y": 0
              },
              "diameter": {
                "value": 90.0,
                "unit": "mm"
              }
            }
          ]
        },
        "parameters": {
          "distance": {
            "value": 6.5,
            "unit": "mm"
          },
          "direction": "normal",
          "operation": "new_body"
        }
      }
    ]
  }
}