#!/usr/bin/env python3
"""
Generated by Claude Code Pattern Analyzer
Pattern: chord_cut
Confidence: 0.93

Analysis:
- All 5 agents unanimously report Circle(diameter=90mm) with bilateral chord cuts
- Audio transcription: "Chapa de diâmetro 90mm Raio de 45mm e 2 linhas a distância de 78mm"
- Visual confirmation: Circular disc with two parallel flat sides
- Pattern: Bilateral chord cuts on cylindrical part (classic D-shaft geometry)
- Height: 27mm (consistent across all agents)
"""

import sys
import json
from pathlib import Path

# Add visioncad src directory to path for imports
# Path structure: .../visioncad/src/docs/outputs/visioncad/SESSION_ID/claude_analysis.py
# We need: .../visioncad/src/ (5 parents up)
visioncad_src = Path(__file__).parent.parent.parent.parent.parent
sys.path.insert(0, str(visioncad_src))

# CRITICAL: Import from semantic_builder (NOT semantic_geometry!)
from semantic_builder import PartBuilder

# Extracted parameters from unanimous agent consensus
diameter = 90.0  # From all agents: geometry.diameter = 90
flat_to_flat = 78.0  # From audio: "2 linhas a distância de 78mm"
height = 27.0  # From all agents: distance = 27
radius = diameter / 2  # 45.0mm (confirmed by audio: "Raio de 45mm")

# Create part using PartBuilder
builder = PartBuilder("chapa_circle_90mm")

# Add chord cut extrude
# This method handles all Arc + Line geometry automatically!
builder.add_chord_cut_extrude(
    radius=radius,
    flat_to_flat=flat_to_flat,
    height=height
)

# Generate semantic JSON
semantic = builder.to_dict()

# Write to file
output_file = Path(__file__).parent / "semantic.json"
with open(output_file, 'w', encoding='utf-8') as f:
    json.dump(semantic, f, indent=2, ensure_ascii=False)

print(f"[OK] Semantic JSON generated: {output_file}")
print(f"   Pattern: chord_cut")
print(f"   Parameters: radius={radius}mm, flat_to_flat={flat_to_flat}mm, height={height}mm")
print(f"   Confidence: 0.93 (unanimous agent consensus)")
print(f"   Source: Claude Code + PartBuilder")
