#!/usr/bin/env python3
"""
Generated by Claude Code Pattern Analyzer
Pattern: hollow_cylinder_with_counterbore_pattern
Confidence: 0.95

Analysis:
- All 5 agents report Circle (D75mm outer, D30mm inner) + 3 counterbore holes
- Audio transcription confirms: "Diametro externo 75mm, diametro interno 30mm,
  3 furos com rebaixo (D9mm hole, D15mm counterbore, 9mm depth) em PCD 50mm"
- Pattern: Hollow cylinder with polar counterbore pattern (3 holes at 120deg spacing)
- Geometry: Base cylinder + center hole + 3 counterbore holes on PCD
"""

import sys
import json
import math
from pathlib import Path

# Add visioncad src directory to path for imports
# Path structure: .../visioncad/src/docs/outputs/visioncad/SESSION_ID/claude_analysis.py
# We need: .../visioncad/src/ (5 parents up)
visioncad_src = Path(__file__).parent.parent.parent.parent.parent
sys.path.insert(0, str(visioncad_src))

from semantic_builder import SemanticGeometryBuilder

# ============================================================================
# EXTRACTED PARAMETERS FROM AGENT RESULTS
# ============================================================================
# All agents consistently reported these values:

# Base geometry (hollow cylinder)
outer_diameter = 75.0    # From agent_results[*].base_geometry.outer_diameter
inner_diameter = 30.0    # From agent_results[*].base_geometry.inner_diameter
base_thickness = 10.0    # Estimated from visual frames (not in transcription)

# Counterbore hole pattern
hole_diameter = 9.0              # From agent_results[*].features[*].hole_diameter
counterbore_diameter = 15.0      # From agent_results[*].features[*].counterbore_diameter
counterbore_depth = 9.0          # From agent_results[*].features[*].counterbore_depth
pattern_count = 3                # From agent_results[*].features[*].pattern_count
pcd = 50.0                       # Pitch Circle Diameter from agent_results[*].features[*].pcd

# ============================================================================
# BUILD PART USING SEMANTICGEOMETRYBUILDER
# ============================================================================

builder = SemanticGeometryBuilder("flange_hollow_75x30_3counterbore")
builder.set_units("mm")
builder.set_work_plane("frontal")

# Step 1: Create base cylinder (D75mm outer)
builder.add_circle_extrusion(
    center=(0, 0),
    diameter=outer_diameter,
    extrude_distance=base_thickness
)

# Step 2: Cut center hole (D30mm) - through all
builder.add_circle_cut(
    center=(0, 0),
    diameter=inner_diameter,
    cut_type="through_all"
)

# Step 3: Add 3 counterbore holes in circular pattern
# Each counterbore = 2 cuts at same position:
#   - Outer cut: D15mm, depth 9mm (for screw head)
#   - Inner cut: D9mm, through_all (for screw shaft)

angle_step = 360.0 / pattern_count  # 120deg spacing for 3 holes

for i in range(pattern_count):
    # Calculate hole center position on PCD
    angle_deg = i * angle_step  # 0deg, 120deg, 240deg
    angle_rad = math.radians(angle_deg)

    x = (pcd / 2) * math.cos(angle_rad)
    y = (pcd / 2) * math.sin(angle_rad)
    center_pos = (round(x, 2), round(y, 2))

    # Outer cut (counterbore - for screw head)
    builder.add_circle_cut(
        center=center_pos,
        diameter=counterbore_diameter,
        cut_type="distance",
        cut_distance=counterbore_depth
    )

    # Inner cut (hole - for screw shaft)
    builder.add_circle_cut(
        center=center_pos,
        diameter=hole_diameter,
        cut_type="through_all"
    )

# ============================================================================
# GENERATE AND SAVE SEMANTIC JSON
# ============================================================================

semantic = builder.build()

output_file = Path(__file__).parent / "semantic.json"
with open(output_file, 'w', encoding='utf-8') as f:
    json.dump(semantic, f, indent=2, ensure_ascii=False)

print(f"[OK] Semantic JSON generated: {output_file}")
print(f"   Pattern: hollow_cylinder_with_counterbore_pattern")
print(f"   Base: D{outer_diameter}mm outer, D{inner_diameter}mm inner, {base_thickness}mm thick")
print(f"   Features: {pattern_count} counterbore holes")
print(f"   Hole: D{hole_diameter}mm, Counterbore: D{counterbore_diameter}mm at {counterbore_depth}mm depth")
print(f"   Pattern: Circular on D{pcd}mm PCD ({angle_step:.0f}deg spacing)")
