#!/usr/bin/env python3
"""
Generated by Claude Code Pattern Analyzer
Pattern: rectangle_extrude
Confidence: 0.95

Analysis:
- All 5 agents unanimously report Rectangle(width=126, height=126) with distance=5mm
- Audio transcription: "Chapa retangular, medida de lado, 126mm por 126mm, 5mm de espessura"
- Visual confirmation: Caliper measurements visible across all frame batches
- No additional features detected (no cuts, holes, pockets, or chamfers)
- Pattern: Simple rectangular plate extrusion

Agent Consensus:
- batch_0: Rectangle 126x126x5, confidence 0.95
- batch_1: Rectangle 126x126x5, confidence 0.95
- batch_2: Rectangle 126x126x5, confidence 0.95
- batch_3: Rectangle 126x126x5, confidence 0.95
- batch_4: Rectangle 126x126x5, confidence 0.95

Decision: Use PartBuilder.add_rectangle_extrude() for simple rectangular plate
"""

import sys
import json
from pathlib import Path

# Add visioncad src directory to path for imports
# Path structure: .../visioncad/src/docs/outputs/visioncad/SESSION_ID/claude_analysis.py
# We need: .../visioncad/src/ (5 parents up)
visioncad_src = Path(__file__).parent.parent.parent.parent.parent
sys.path.insert(0, str(visioncad_src))

from semantic_builder import SemanticGeometryBuilder

# Extracted parameters from agent results (unanimous agreement)
width = 126.0  # From agent_results[*].features[0].geometry.width
height = 126.0  # From agent_results[*].features[0].geometry.height
depth = 5.0  # From agent_results[*].features[0].distance (thickness/extrusion depth)

# Create part using SemanticGeometryBuilder
builder = SemanticGeometryBuilder("chapa_retangular_126x126x5")
builder.set_units("mm")
builder.set_work_plane("frontal")

# Add rectangular extrusion
builder.add_rectangle_extrusion(
    center=(0, 0),
    width=width,
    height=height,
    extrude_distance=depth
)

# Generate semantic JSON
semantic = builder.build()

# Write to file
output_file = Path(__file__).parent / "semantic.json"
with open(output_file, 'w', encoding='utf-8') as f:
    json.dump(semantic, f, indent=2, ensure_ascii=False)

print(f"[OK] Semantic JSON generated: {output_file}")
print(f"   Pattern: rectangle_extrude")
print(f"   Parameters: width={width}mm, height={height}mm, depth={depth}mm")
print(f"   Confidence: 0.95 (unanimous agent agreement)")
