#!/usr/bin/env python3
"""
Generated by Claude Code Pattern Analyzer
Pattern: chord_cut (bilateral symmetric cuts)
Confidence: 0.90

Analysis:
- All 5 agents consistently report Circle(diameter=90mm) + bilateral cuts
- Agent consensus:
  * Base: Circle extrude, diameter=90mm, height=5mm (avg confidence: 0.93)
  * Cut 1: Rectangle cut, position="left_side", depth=6mm (avg confidence: 0.88)
  * Cut 2: Rectangle cut, position="right_side", depth=6mm (avg confidence: 0.89)

- Audio transcription: "Chapa de diâmetro 90mm Raio de 45mm e 2 linhas a distância de 78mm"
  * Diameter: 90mm → radius = 45mm
  * "2 linhas a distância de 78mm" → flat-to-flat distance = 78mm
  * Height: 5mm (from visual measurements in frames)

- Pattern recognition:
  * Bilateral cuts with positions "left_side" + "right_side"
  * Geometric constraint: (diameter - flat_to_flat) / 2 = cut_depth
  * Verification: (90 - 78) / 2 = 6mm ✓ (matches agent reports)

- Conclusion: This is a CHORD CUT pattern
  * Method to use: add_chord_cut_extrude()
  * Parameters extracted from data (not estimated)
"""

import sys
import json
from pathlib import Path

# Add visioncad src directory to path for imports
# Path structure: .../visioncad/src/docs/outputs/visioncad/SESSION_ID/claude_analysis.py
# We need: .../visioncad/src/ (go up 5 parents to reach src/)
# parent = SESSION_ID, parent.parent = visioncad, parent^3 = outputs, parent^4 = docs, parent^5 = src
visioncad_src = Path(__file__).parent.parent.parent.parent.parent
sys.path.insert(0, str(visioncad_src))

# CRITICAL: Import from semantic_builder (in visioncad/src/), NOT semantic_geometry!
from semantic_builder import PartBuilder

# Extracted parameters (from agent consensus + audio transcription)
diameter = 90.0  # All agents report: geometry.diameter = 90
radius = diameter / 2  # 45.0mm (confirmed by audio "Raio de 45mm")
flat_to_flat = 78.0  # From audio: "2 linhas a distância de 78mm"
height = 5.0  # Agent consensus: distance = 5mm (extrusion height)

# Validation
cut_depth_expected = (diameter - flat_to_flat) / 2  # Should be 6mm
print(f"[VALIDATION] Cut depth calculation: ({diameter} - {flat_to_flat}) / 2 = {cut_depth_expected}mm")
print(f"[VALIDATION] Agent reported cut depth: 6mm")
print(f"[VALIDATION] Match: {abs(cut_depth_expected - 6.0) < 0.01}")

# Create part using PartBuilder
part_name = "chapa_circle_90mm"
builder = PartBuilder(part_name)

# Add chord cut extrude
# This method automatically generates Arc + Line geometry for bilateral cuts
builder.add_chord_cut_extrude(
    radius=radius,           # 45.0mm
    flat_to_flat=flat_to_flat,  # 78.0mm
    height=height            # 5.0mm
)

# Generate semantic JSON
semantic = builder.to_dict()

# Write to file
output_file = Path(__file__).parent / "semantic.json"
with open(output_file, 'w', encoding='utf-8') as f:
    json.dump(semantic, f, indent=2, ensure_ascii=False)

print(f"[OK] Semantic JSON generated: {output_file}")
print(f"   Pattern: chord_cut")
print(f"   Parameters:")
print(f"     - radius: {radius}mm")
print(f"     - flat_to_flat: {flat_to_flat}mm")
print(f"     - height: {height}mm")
print(f"   Confidence: 0.90 (high agent consensus)")
