#!/usr/bin/env python3
"""
Generated by Claude Code Pattern Analyzer
Pattern: chord_cut
Confidence: 0.98

Analysis:
EXTREMELY STRONG EVIDENCE for chord_cut pattern:

1. UNANIMOUS VISUAL CONSENSUS (5/5 agents, 100% agreement):
   - All 5 agents independently report Circle base (diameter=90mm, height=27mm)
   - All 5 agents report bilateral cuts: position='left_side' + position='right_side'
   - Perfect symmetry: 5 left cuts + 5 right cuts across all agents
   - Consistent cut depth: 6mm per side (all agents)
   - Cut calculation verified: (90-78)/2 = 6mm ✓

2. AUDIO TRANSCRIPTION EXPLICITLY CONFIRMS:
   - 'Chapa de diâmetro 90mm' → circle base
   - 'Raio de 45mm' → radius confirmation (90/2 = 45 ✓)
   - '2 linhas a distância de 78mm' → EXPLICIT flat-to-flat distance
   - This is a DIRECT statement of the chord cut parameter!

3. MANUFACTURING LOGIC VALIDATES:
   - Original diameter: 90mm
   - Flat-to-flat distance: 78mm
   - Cut depth per side: (90-78)/2 = 6mm
   - Agent reports: 6mm depth ✓ (EXACT MATCH!)
   - This is textbook bilateral chord cut geometry

4. AGENT NOTES PROVIDE ADDITIONAL CONFIDENCE:
   - Agents explicitly mention 'chord cut', 'D-shaft', 'double-flat'
   - Multiple agents reference caliper measurements confirming dimensions
   - Agents describe 'circle with two parallel straight segments'

CONCLUSION: This is unequivocally a chord_cut pattern with the highest possible
confidence. All evidence sources (visual, audio, manufacturing logic, agent reasoning)
converge perfectly with ZERO contradictions or ambiguity.
"""

import sys
import json
from pathlib import Path

# Add visioncad src directory to path for imports
# We're in: .../visioncad/src/docs/outputs/visioncad/SESSION_ID/claude_analysis.py
# We need: .../visioncad/src/ (5 parents: SESSION_ID -> visioncad -> outputs -> docs -> src)
visioncad_src = Path(__file__).parent.parent.parent.parent.parent
sys.path.insert(0, str(visioncad_src))

from semantic_builder import PartBuilder

# Extracted parameters from unanimous agent consensus
diameter = 90.0  # From all 5 agents: geometry.diameter = 90
flat_to_flat = 78.0  # From audio: "2 linhas a distância de 78mm"
height = 27.0  # From all 5 agents: distance = 27
radius = diameter / 2  # 45.0mm (confirmed by audio: "Raio de 45mm")

# Create part using PartBuilder
builder = PartBuilder("chapa_circle_90mm")

# Add chord cut extrude
builder.add_chord_cut_extrude(
    radius=radius,
    flat_to_flat=flat_to_flat,
    height=height
)

# Generate semantic JSON
semantic = builder.to_dict()

# Write to file
output_file = Path(__file__).parent / "semantic.json"
with open(output_file, 'w', encoding='utf-8') as f:
    json.dump(semantic, f, indent=2, ensure_ascii=False)

print(f"[OK] Semantic JSON generated: {output_file}")
print(f"   Pattern: chord_cut")
print(f"   Parameters: radius={radius}mm, flat_to_flat={flat_to_flat}mm, height={height}mm")
print(f"   Confidence: 0.98 (unanimous agent consensus)")
