#!/usr/bin/env python3
"""
Generated by Claude Code Pattern Analyzer
Pattern: chord_cut
Confidence: 0.93

Analysis:
- All 5 agents consistently report Circle(diameter=90mm) base geometry
- All agents detect bilateral parallel cuts creating 78mm flat-to-flat distance
- Agent consensus: 2 symmetric cuts on left_side/right_side positions
- Audio transcription: "Chapa de diâmetro 90mm Raio de 45mm e 2 linhas a distância de 78mm"
- Height: 27mm (consensus across all agents)
- Cut depth: (90-78)/2 = 6mm per side

Pattern: Bilateral chord cuts on cylindrical part (D-shaped profile)
"""

import sys
import json
from pathlib import Path

# Add visioncad src directory to path for imports
# Path structure: .../visioncad/src/docs/outputs/visioncad/SESSION_ID/claude_analysis.py
# We need: .../visioncad/src/ (5 parents up)
visioncad_src = Path(__file__).parent.parent.parent.parent.parent
sys.path.insert(0, str(visioncad_src))

# Import from semantic_builder (in visioncad/src/)
from semantic_builder import PartBuilder

# Load request to check for user-provided measurements
request_file = Path(__file__).parent / ".claude_analysis_request.json"
with open(request_file, encoding='utf-8') as f:
    request = json.load(f)

# Extract parameters from agent results and transcription
agent_results = request["agent_results"]
transcription = request.get("transcription", "")

# Get diameter from agent consensus (all report 90mm)
diameter = 90.0  # From agent_results[*].geometry.diameter
radius = diameter / 2  # 45mm

# Get flat-to-flat from transcription: "2 linhas a distância de 78mm"
flat_to_flat = 78.0

# Get height from agent consensus (all report 27mm)
height = 27.0  # From agent_results[*].distance

# Check if user provided measurements
if "[Medições fornecidas:" in transcription or "[Medicoes fornecidas:" in transcription:
    import re
    match = re.search(r'\[Medi[çc]ões fornecidas: (.*?)\]', transcription)
    if match:
        measurements_str = match.group(1)
        # Parse: "diameter=90.0mm, height=27.0mm"
        for item in measurements_str.split(','):
            name, value = item.strip().split('=')
            value_num = float(value.replace('mm', ''))
            if name == "diameter":
                diameter = value_num
                radius = diameter / 2
                print(f"  [USER PROVIDED] diameter = {value_num}mm")
            elif name == "height":
                height = value_num
                print(f"  [USER PROVIDED] height = {value_num}mm")

print(f"\n[CLAUDE ANALYSIS] Pattern: chord_cut")
print(f"  radius: {radius}mm")
print(f"  flat_to_flat: {flat_to_flat}mm")
print(f"  height: {height}mm")

# Create part using PartBuilder
builder = PartBuilder("chapa_circle_90mm")

# Add chord cut extrude (handles Arc + Line geometry automatically)
builder.add_chord_cut_extrude(
    radius=radius,
    flat_to_flat=flat_to_flat,
    height=height
)

# Generate semantic JSON
semantic = builder.to_dict()

# Write to file
output_file = Path(__file__).parent / "semantic.json"
with open(output_file, 'w', encoding='utf-8') as f:
    json.dump(semantic, f, indent=2, ensure_ascii=False)

print(f"[OK] Semantic JSON generated: {output_file.name}")
print(f"   Pattern: chord_cut")
print(f"   Parameters: radius={radius}mm, flat_to_flat={flat_to_flat}mm, height={height}mm")
